import type { Metadata } from "next";
import "./globals.css";
import { plusJakartaSans } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Frontend Mentor | Notification Page",
  description: "Generated by Karim Ayman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable}`}>{children}</body>
    </html>
  );
}
